### ISSUE TITLE
Microsoft Changes the location of Logs

### ISSUE THREAD

**Issue by jonnwhite1** [ThomasKur/IntuneConnectorForADExtender#4]
Hi, 

I've been using this tool for a long while and it's great!
I was doing maintenance and updated our Connector to the latest version and Microsoft have changes the Event Viewer location. 
I tried to put in the new location into the settings file (Below how i did it) however the service then fails to start. 
Luckily i kept the installer for the older version so managed to roll back and get it going again. 

Any tips as i'd like to not get too far behind!    

<setting name="LogName" serializeAs="String">
                <value>Microsoft-Intune-ODJConnectorService/Admin</value>
            </setting>
            <setting name="LogSource" serializeAs="String">
                <value>ODJConnectorService</value>
            </setting>

**Comment by LM-J** [comment]
Hi @ThomasKur, I am having the same issue as jonnwhite1.  The connector is broken after a Microsoft update.  I did try to change config files also, but the application didn't start.  I believe an application update is needed for: 
 IntuneConnectorForADExtender.Service.exe

**Comment by ThomasKur** [comment]
Thank you for the feedback. I just saw this too but I have currently no testenvironment available for it so I share the simple solution here: 

- Locate the config file in the install directory 
- Modify the LogName and LogSource value to the new one
- Restart service
- Test if it works

![image](https://user-images.githubusercontent.com/16786269/203912454-6796859f-d155-40f5-b696-374154f1199c.jpeg)

Please inform me if all works, then I can also adjust the setup.

**Comment by LM-J** [comment]
Hi @ThomasKur, many thanks for picking this up, we use this application in conjunction with our Autopilot setup and it is VERY useful, so I much appreciate your assistance! :)

I have some troubleshooting detail for you.  There are 2 config files referencing the windows logs:

IntuneConnectorForADExtender.ConsoleApp.exe.config
IntuneConnectorForADExtender.Service.exe.config

I tried your suggestion to modify the config:  IntuneConnectorForADExtender.Service.exe.config
but it errors out.

This is the part I modified:

![image](https://user-images.githubusercontent.com/118901102/204018201-703f9aad-972a-41cb-8d4e-a9580970ffae.png)

I got the log name and source from the windows log itself (in the hope this was correct):

![image](https://user-images.githubusercontent.com/118901102/204018364-383b5763-3f66-45f6-892d-714319faa1ac.png)

Restarted the service and it errors:

![image](https://user-images.githubusercontent.com/118901102/204018797-1836d32e-0e68-4d63-8034-8d91ead7bdb3.png)
![image](https://user-images.githubusercontent.com/118901102/204018873-71759350-3f22-4a08-a757-88fdabaa8c45.png)

I then proceeded to change the config file:  IntuneConnectorForADExtender.ConsoleApp.exe.config

I modified this part to match the other config file:
![image](https://user-images.githubusercontent.com/118901102/204019062-f9951f99-ba80-4aef-82af-d8abbbd32ae3.png)

And the service still errors out (same error as above).

Hopefully this is all helpful, so that you can make adjustments / code changes?

Many thanks!

**Comment by jonnwhite1** [comment]
I had the same issue when I changed the config files, i don't think the app can recognise folders :( luckily i've managed to keep mine on a version which works with Extender however i imagine at some point it will stop working.

**Comment by ThomasKur** [comment]
Yes, you got the point. I work on a solution

**Comment by ThomasKur** [comment]
Ok, I have to rewrite nearly all code as the System.Diagnostic method used in code does not support subfolders. This requires to test everything again after the change. For this I need to setup a test environment and invest time. So I will check if Hybrid Join including my module is still used in the community and then decide if I will  do the work. If it is used just in a few environments, then I highly recommend to switch to AAD join only as it simplifies the life.

https://twitter.com/ThomasKurth_ch/status/1600832964941606912

**Comment by jonnwhite1** [comment]
Thank you, unfortunately for us Azure AD join isn't working as we have lots of legacy stuff and still use machine auth for certain systems. We are trailing but something simple like SCCM remote control doesn't work, if you decid not to develop it would you share the source code if not already shared?

**Comment by ThomasKur** [comment]
@jonnwhite1 yes I have checked all the feedback and just a few are still using the solution and as I have no test environment it would be a huge time investment t to setup it on my side. The source code is here on GitHub. Feel free to create a own branch and commit back to the main repo as soon you have tested it.
